from flask import Flask, render_template, jsonify, request, send_from_directory, redirect, url_for, send_file
import json, os, uuid
import psycopg2
import psycopg2.extras
from pathlib import Path
from datetime import datetime
from werkzeug.utils import secure_filename
from openpyxl import Workbook
from supabase import create_client

BASE = Path(__file__).resolve().parent
IMG = BASE / 'images'
EXPORT = BASE / 'escolhas.xlsx'
ALLOWED = {'.png', '.jpg', '.jpeg', '.webp', '.gif'}

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 8 * 1024 * 1024


@app.before_request
def protect_admin():
    if request.path.startswith('/admin'):
        admin_password = os.environ.get('ADMIN_PASSWORD')
        auth = request.authorization

        if (
            not admin_password
            or not auth
            or auth.username != 'admin'
            or auth.password != admin_password
        ):
            return (
                'Acesso restrito',
                401,
                {'WWW-Authenticate': 'Basic realm="Painel administrativo"'}
            )


def conn():
    return psycopg2.connect(
        os.environ['DATABASE_URL'],
        cursor_factory=psycopg2.extras.RealDictCursor
    )


def export_choices(c=None):
    own = c is None

    if own:
        c = conn()

    with c.cursor() as cur:
        cur.execute(
            '''
            SELECT h.id, h.guest_name, h.gift_name, h.chosen_at, h.active
            FROM choice_history h
            ORDER BY h.id DESC
            '''
        )
        rows = cur.fetchall()

    wb = Workbook()
    ws = wb.active
    ws.title = 'Escolhas'

    ws.append([
        'Nome do convidado',
        'Presente escolhido',
        'Data e hora',
        'Status'
    ])

    for r in rows:
        ws.append([
            r['guest_name'],
            r['gift_name'],
            r['chosen_at'],
            'Ativa' if r['active'] else 'Liberada'
        ])

    ws.column_dimensions['A'].width = 28
    ws.column_dimensions['B'].width = 42
    ws.column_dimensions['C'].width = 22
    ws.column_dimensions['D'].width = 14

    wb.save(EXPORT)

    if own:
        c.close()


def init_db():
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                CREATE TABLE IF NOT EXISTS gifts(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    link TEXT,
                    image TEXT,
                    status TEXT NOT NULL DEFAULT 'disponivel',
                    chosen_by TEXT,
                    chosen_at TEXT
                )
                '''
            )

            cur.execute(
                '''
                CREATE TABLE IF NOT EXISTS settings(
                    key TEXT PRIMARY KEY,
                    value TEXT
                )
                '''
            )

            cur.execute(
                '''
                CREATE TABLE IF NOT EXISTS choice_history(
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    gift_id INTEGER,
                    guest_name TEXT NOT NULL,
                    gift_name TEXT NOT NULL,
                    chosen_at TEXT NOT NULL,
                    active INTEGER NOT NULL DEFAULT 1
                )
                '''
            )

            cur.execute('SELECT COUNT(*) AS n FROM gifts')
            count = cur.fetchone()['n']

            if count == 0:
                data = json.loads(
                    (BASE / 'items.json').read_text(encoding='utf-8')
                )

                for item in data:
                    cur.execute(
                        '''
                        INSERT INTO gifts(id, name, link, image)
                        VALUES(%s, %s, %s, %s)
                        ''',
                        (
                            item['id'],
                            item['name'],
                            item.get('link'),
                            item.get('image')
                        )
                    )

            defaults = {
                'title': 'Lista de Presentes',
                'subtitle': 'Chá de Panela',
                'couple': 'Paola & Ruan',
                'intro': 'Cada presente escolhido com amor levará um pedacinho de vocês para o nosso novo lar, fazendo parte dos sonhos e da linda história que estamos construindo juntos.',
                'primary': '#82a8c5',
                'secondary': '#d8edf9',
                'background': '#fbfaf5'
            }

            for k, v in defaults.items():
                cur.execute(
                    '''
                    INSERT INTO settings(key, value)
                    VALUES(%s, %s)
                    ON CONFLICT (key) DO NOTHING
                    ''',
                    (k, v)
                )

        c.commit()

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()


@app.get('/images/<path:name>')
def images(name):
    return send_from_directory(IMG, name)


@app.get('/')
def home():
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                SELECT id, name, link, image, status
                FROM gifts
                ORDER BY id
                '''
            )
            gifts = [dict(r) for r in cur.fetchall()]

            cur.execute('SELECT key, value FROM settings')
            settings = {
                r['key']: r['value']
                for r in cur.fetchall()
            }

    finally:
        c.close()

    return render_template(
        'index.html',
        gifts=gifts,
        settings=settings
    )


@app.get('/api/gifts')
def gifts_api():
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                SELECT id, name, link, image, status
                FROM gifts
                ORDER BY id
                '''
            )
            data = [dict(r) for r in cur.fetchall()]

    finally:
        c.close()

    return jsonify(data)


@app.post('/api/reserve/<int:gift_id>')
def reserve(gift_id):
    name = (request.json or {}).get('name', '').strip()

    if not name:
        return jsonify(
            ok=False,
            message='Digite seu nome.'
        ), 400

    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                SELECT name, status
                FROM gifts
                WHERE id=%s
                FOR UPDATE
                ''',
                (gift_id,)
            )

            row = cur.fetchone()

            if not row:
                c.rollback()
                return jsonify(
                    ok=False,
                    message='Presente não encontrado.'
                ), 404

            if row['status'] != 'disponivel':
                c.rollback()
                return jsonify(
                    ok=False,
                    message='Esse presente acabou de ser escolhido por outra pessoa. Escolha outro presente.'
                ), 409

            now = datetime.now().strftime('%d/%m/%Y %H:%M:%S')

            cur.execute(
                '''
                UPDATE gifts
                SET status='escolhido',
                    chosen_by=%s,
                    chosen_at=%s
                WHERE id=%s
                  AND status='disponivel'
                ''',
                (name, now, gift_id)
            )

            if cur.rowcount != 1:
                c.rollback()
                return jsonify(
                    ok=False,
                    message='Esse presente acabou de ser escolhido por outra pessoa. Escolha outro presente.'
                ), 409

            cur.execute(
                '''
                INSERT INTO choice_history(
                    gift_id,
                    guest_name,
                    gift_name,
                    chosen_at
                )
                VALUES(%s, %s, %s, %s)
                ''',
                (
                    gift_id,
                    name,
                    row['name'],
                    now
                )
            )

        c.commit()

        return jsonify(
            ok=True,
            message='Presente escolhido com carinho! Obrigada por fazer parte desse momento tão especial.'
        )

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()



def save_upload(file):
    if not file or not file.filename:
        return None

    ext = Path(secure_filename(file.filename)).suffix.lower()

    if ext not in ALLOWED:
        raise ValueError('Formato de imagem não permitido.')

    name = f'gift-{uuid.uuid4().hex}{ext}'

    supabase = create_client(
        os.environ['SUPABASE_URL'],
        os.environ['SUPABASE_KEY']
    )

    file.stream.seek(0)
    supabase.storage.from_('presentes').upload(
        path=name,
        file=file.stream.read(),
        file_options={
            'content-type': file.mimetype or 'application/octet-stream',
            'upsert': 'false'
        }
    )

    return supabase.storage.from_('presentes').get_public_url(name)



@app.route('/admin', methods=['GET', 'POST'])
def admin():
    c = conn()

    try:
        with c.cursor() as cur:
            if request.method == 'POST':
                for k in [
                    'title',
                    'subtitle',
                    'couple',
                    'intro',
                    'primary',
                    'secondary',
                    'background'
                ]:
                    cur.execute(
                        '''
                        INSERT INTO settings(key, value)
                        VALUES(%s, %s)
                        ON CONFLICT (key)
                        DO UPDATE SET value=EXCLUDED.value
                        ''',
                        (
                            k,
                            request.form.get(k, '')
                        )
                    )

                c.commit()
                return redirect(url_for('admin'))

            cur.execute(
                'SELECT * FROM gifts ORDER BY id'
            )
            gifts = [
                dict(r)
                for r in cur.fetchall()
            ]

            cur.execute(
                'SELECT key, value FROM settings'
            )
            settings = {
                r['key']: r['value']
                for r in cur.fetchall()
            }

            cur.execute(
                '''
                SELECT *
                FROM choice_history
                ORDER BY id DESC
                LIMIT 100
                '''
            )
            history = [
                dict(r)
                for r in cur.fetchall()
            ]

    finally:
        c.close()

    return render_template(
        'admin.html',
        gifts=gifts,
        settings=settings,
        history=history
    )


@app.post('/admin/gift/add')
def add_gift():
    name = request.form.get(
        'name',
        ''
    ).strip()

    link = request.form.get(
        'link',
        ''
    ).strip()

    if not name:
        return redirect(url_for('admin'))

    try:
        image = save_upload(
            request.files.get('image')
        )
    except ValueError:
        image = None

    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                INSERT INTO gifts(name, link, image)
                VALUES(%s, %s, %s)
                ''',
                (name, link, image)
            )

        c.commit()

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()

    return redirect(url_for('admin'))


@app.post('/admin/gift/<int:gift_id>/edit')
def edit_gift(gift_id):
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                SELECT image
                FROM gifts
                WHERE id=%s
                ''',
                (gift_id,)
            )

            row = cur.fetchone()

            if not row:
                return redirect(url_for('admin'))

            image = row['image']

            try:
                new = save_upload(
                    request.files.get('image')
                )
                image = new or image
            except ValueError:
                pass

            cur.execute(
                '''
                UPDATE gifts
                SET name=%s,
                    link=%s,
                    image=%s
                WHERE id=%s
                ''',
                (
                    request.form.get(
                        'name',
                        ''
                    ).strip(),
                    request.form.get(
                        'link',
                        ''
                    ).strip(),
                    image,
                    gift_id
                )
            )

        c.commit()

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()

    return redirect(url_for('admin'))


@app.post('/admin/gift/<int:gift_id>/delete')
def delete_gift(gift_id):
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                DELETE FROM gifts
                WHERE id=%s
                ''',
                (gift_id,)
            )

        c.commit()

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()

    return redirect(url_for('admin'))


@app.post('/admin/reset/<int:gift_id>')
def reset(gift_id):
    c = conn()

    try:
        with c.cursor() as cur:
            cur.execute(
                '''
                UPDATE gifts
                SET status='disponivel',
                    chosen_by=NULL,
                    chosen_at=NULL
                WHERE id=%s
                ''',
                (gift_id,)
            )

            cur.execute(
                '''
                UPDATE choice_history
                SET active=0
                WHERE gift_id=%s
                  AND active=1
                ''',
                (gift_id,)
            )

        c.commit()

    except Exception:
        c.rollback()
        raise

    finally:
        c.close()

    return redirect(url_for('admin'))


@app.get('/admin/escolhas.xlsx')
def download_choices():
    export_choices()

    return send_file(
        EXPORT,
        as_attachment=True,
        download_name='escolhas-cha-de-panela.xlsx'
    )


init_db()

if __name__ == '__main__':
    app.run(
        host='0.0.0.0',
        port=int(os.environ.get('PORT', 5000)),
        debug=False
    )
